services:
  postgres:
    image: postgres:latest
    container_name: ms_clients_postgres
    hostname: ms_clients_postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  
  app:
    depends_on:
      - postgres
    build: 
      context: .
    container_name: ms_clients_app
    hostname: ms_clients_app
    restart: unless-stopped
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUGGER_LOCAL_PORT}:${DEBUGGER_DOCKER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DOCKER_PORT=${POSTGRES_DOCKER_PORT}
    networks:
      - backend


volumes:
  db-data:

networks:
  backend: