services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  
  app:
    depends_on:
      - postgres
    build: 
      context: .
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DOCKER_PORT=${POSTGRES_DOCKER_PORT}
    networks:
      - backend


volumes:
  db-data:

networks:
  backend: