name: 'mspr-monitoring-services'
services:
  # Service for RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/rabbitmq
    networks:
      - monitoring

  # Service for Prometheus
  prometheus:
    container_name: prometheus-service
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - monitoring

  # Service for Grafana loki
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  # Service for Grafana tempo
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo/tempo-config.yaml
    volumes:
      - ./tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml
    ports:
      - "3200:3200"     # Tempo
      - "9411:9411"    # Zipkin
    networks:
      - monitoring

  # Service for Grafana
  grafana:
    container_name: grafana-service
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: { }
  rabbit_data: { }